build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - mvn package
    - export PORT=5000
    - fuser -k 5000/tcp
    - sudo nohup target/bin/simplewebapp > output.txt 2>&1 &

deploy_to_heroku:
  stage: deploy
  script: 
    - dpl --provider=heroku --app=lst2020-simplewebapp --api-key=c9e71872-c9f2-42ec-848e-9db399acd214
